"""
Core text processing module for Clean Paste.
Handles Unicode character stripping, typography normalization, and statistical rephrasing.
"""

import re
import unicodedata

# Mapping dictionary for typography normalization
TYPOGRAPHY_MAP = {
    # Smart double quotes
    '“': '"',
    '”': '"',
    '„': '"',
    '‟': '"',
    # Smart single quotes and apostrophes
    '‘': "'",
    '’': "'",
    '‚': "'",
    '‛': "'",
    # Dashes
    '—': '-',  # Em-dash
    '–': '-',  # En-dash
    '‒': '-',  # Figure dash
    # Ellipsis
    '…': '...',
    # Non-breaking spaces and other layout spaces
    '\u00a0': ' ',  # No-break space
    '\u2007': ' ',  # Figure space
    '\u202f': ' ',  # Narrow no-break space
    '\u202f': ' ',  # Narrow no-break space
    '\ufeff': '',   # Byte-order mark (strip completely)
}

# Statistical patterns commonly generated by LLMs and their humanized/simplified alternatives.
# Used to strip statistical watermarks / rephrase text slightly.
STATISTICAL_REPLACEMENTS = [
    # Sentence starters and transitions
    (r'\bFurthermore\b,', 'Also,'),
    (r'\bMoreover\b,', 'In addition,'),
    (r'\bAdditionally\b,', 'Also,'),
    (r'\bConsequently\b,', 'So,'),
    (r'\bTherefore\b,', 'Thus,'),
    (r'\bIn conclusion\b,', 'To sum up,'),
    (r'\bIt is important to note that\b', 'Note that'),
    (r'\bNeedless to say\b,', 'Obviously,'),
    (r'\bFirst and foremost\b,', 'First,'),
    (r'\bLast but not least\b,', 'Finally,'),
    
    # Overused LLM verbs/phrases
    (r'\butilize\b', 'use'),
    (r'\butilizes\b', 'uses'),
    (r'\butilizing\b', 'using'),
    (r'\butilization\b', 'use'),
    (r'\bdelve into\b', 'explore'),
    (r'\bdelves into\b', 'explores'),
    (r'\bdelving into\b', 'exploring'),
    (r'\btapestry\b', 'complex structure'),
    (r'\bbeacon of\b', 'example of'),
    (r'\btestament to\b', 'proof of'),
    (r'\bnot only ([^,.]+?) but also\b', r'\1 and also'),
]


def strip_hidden_characters(text: str) -> str:
    """
    Remove hidden format characters, zero-width characters, and invisible layout codes.
    Preserves standard whitespace characters (newlines, carriage returns, tabs).
    """
    if not text:
        return ""
        
    cleaned = []
    for char in text:
        # Get Unicode category
        cat = unicodedata.category(char)
        
        # Cf: Other, Format (e.g. Zero-Width Space U+200B, ZWNJ U+200C, ZWJ U+200D)
        # Cs: Other, Surrogate
        # Co: Other, Private Use
        if cat in ('Cf', 'Cs'):
            continue
            
        # Cc: Other, Control (e.g. carriage return, line feed, tab)
        # We must preserve \n, \r, and \t
        if cat == 'Cc' and char not in ('\n', '\r', '\t'):
            continue
            
        # Extra safety for known zero-width and BOM characters
        if char in ('\u200b', '\u200c', '\u200d', '\u200e', '\u200f', '\ufeff'):
            continue
            
        cleaned.append(char)
        
    return "".join(cleaned)


def normalize_typography(text: str) -> str:
    """
    Normalize typography style by replacing smart quotes, non-standard dashes,
    and non-breaking spaces with standard typewriter equivalents.
    """
    if not text:
        return ""
        
    # Translate single characters according to map
    translation_table = str.maketrans(TYPOGRAPHY_MAP)
    return text.translate(translation_table)


def statistical_paraphrase(text: str) -> str:
    """
    Apply local replacement rules to reduce standard statistical markers (typical LLM writing patterns)
    while preserving original meaning.
    """
    if not text:
        return ""
        
    processed = text
    for pattern, replacement in STATISTICAL_REPLACEMENTS:
        # Case insensitive replacements but keeping case for the replacement if it is at the start of sentence
        # Simple implementation using re.sub with regex patterns
        # We compile pattern as case-insensitive to match variations (e.g. "Furthermore" vs "furthermore")
        compiled = re.compile(pattern, re.IGNORECASE)
        
        def replace_with_case(match):
            matched_text = match.group(0)
            # If the matched word started with uppercase, uppercase the replacement
            if matched_text and matched_text[0].isupper():
                # If there are backreferences in replacement
                if '\\' in replacement or r'\\' in replacement or '$' in replacement:
                    # Resolve replacement group
                    # Wait, let's keep it simple. If we match group backreferences, we replace.
                    # For simple replacements, just capitalize the first character
                    resolved = match.expand(replacement)
                    return resolved[0].upper() + resolved[1:] if resolved else resolved
                else:
                    return replacement[0].upper() + replacement[1:]
            return match.expand(replacement)
            
        processed = compiled.sub(replace_with_case, processed)
        
    # Replace double spaces that might result from replacement or were pre-existing
    processed = re.sub(r' +', ' ', processed)
    return processed
